In [8]:
import numpy as np
import pandas as pd

Exception ignored in PyObject_HasAttr(); consider using PyObject_HasAttrWithError(), PyObject_GetOptionalAttr() or PyObject_GetAttr():
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
AttributeError: partially initialized module 'pandas' from 'e:\Generative AI with Langchain and Huggingface\venv\Lib\site-packages\pandas\__init__.py' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)

## Creating DataFrame

In [9]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 28, 35, 27],
    "City": ["New York", "London", "Mumbai", "Sydney", "Toronto"],
    "Salary": [55000, 62000, 48000, 75000, 59000]
}

df1 = pd.DataFrame(data)

In [10]:
df1

      Name  Age      City  Salary
0    Alice   25  New York   55000
1      Bob   30    London   62000
2  Charlie   28    Mumbai   48000
3    David   35    Sydney   75000
4     Emma   27   Toronto   59000

In [11]:
data_list=[
    ["Alice", 25, "New York", 55000],
    ["Bob", 30, "London", 62000],
    ["Charlie", 28, "Mumbai", 48000],
    ["David", 35, "Sydney", 75000],
    ["Emma", 27, "Toronto", 59000]
]

df2=pd.DataFrame(data_list)

In [12]:
df2

         0   1         2      3
0    Alice  25  New York  55000
1      Bob  30    London  62000
2  Charlie  28    Mumbai  48000
3    David  35    Sydney  75000
4     Emma  27   Toronto  59000

In [13]:
df3=pd.DataFrame(data_list,columns=["Name","Age","City","Salary"])
df3

      Name  Age      City  Salary
0    Alice   25  New York   55000
1      Bob   30    London   62000
2  Charlie   28    Mumbai   48000
3    David   35    Sydney   75000
4     Emma   27   Toronto   59000

## Selection and Indexing of Columns

In [14]:
df3

      Name  Age      City  Salary
0    Alice   25  New York   55000
1      Bob   30    London   62000
2  Charlie   28    Mumbai   48000
3    David   35    Sydney   75000
4     Emma   27   Toronto   59000

In [15]:
df3["Name"]

0      Alice
1        Bob
2    Charlie
3      David
4       Emma
Name: Name, dtype: str

In [16]:
df3[["Name", "Salary"]]

      Name  Salary
0    Alice   55000
1      Bob   62000
2  Charlie   48000
3    David   75000
4     Emma   59000

## Creating a new Column

In [17]:
df3["Gender"]=["Female", "Male", "Male", "Male", "Female"]
df3

      Name  Age      City  Salary  Gender
0    Alice   25  New York   55000  Female
1      Bob   30    London   62000    Male
2  Charlie   28    Mumbai   48000    Male
3    David   35    Sydney   75000    Male
4     Emma   27   Toronto   59000  Female

## Removing Columns

In [18]:
df3

      Name  Age      City  Salary  Gender
0    Alice   25  New York   55000  Female
1      Bob   30    London   62000    Male
2  Charlie   28    Mumbai   48000    Male
3    David   35    Sydney   75000    Male
4     Emma   27   Toronto   59000  Female

In [19]:
df3.drop("Gender", axis=1, inplace=True)
df3

      Name  Age      City  Salary
0    Alice   25  New York   55000
1      Bob   30    London   62000
2  Charlie   28    Mumbai   48000
3    David   35    Sydney   75000
4     Emma   27   Toronto   59000

In [20]:
df3.drop(["City", "Salary"], axis=1)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   28
3    David   35
4     Emma   27

In [21]:
df3.drop(0,axis=0)

      Name  Age     City  Salary
1      Bob   30   London   62000
2  Charlie   28   Mumbai   48000
3    David   35   Sydney   75000
4     Emma   27  Toronto   59000

## Selecting Rows

In [22]:
df3

      Name  Age      City  Salary
0    Alice   25  New York   55000
1      Bob   30    London   62000
2  Charlie   28    Mumbai   48000
3    David   35    Sydney   75000
4     Emma   27   Toronto   59000

In [ ]:
df3.loc[0]

Name         Alice
Age             25
City      New York
Salary       55000
Name: 0, dtype: object

In [ ]:
df3.loc[[0,1]]

    Name  Age      City  Salary
0  Alice   25  New York   55000
1    Bob   30    London   62000

## Selecting Subsets of Rows and Columns

In [ ]:
df3

      Name  Age      City  Salary
0    Alice   25  New York   55000
1      Bob   30    London   62000
2  Charlie   28    Mumbai   48000
3    David   35    Sydney   75000
4     Emma   27   Toronto   59000

In [ ]:
df3.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   55000
1    London   62000

In [ ]:
df3.loc[[3,4]][["Name","Age"]]

    Name  Age
3  David   35
4   Emma   27

## Conditional Selection

In [ ]:
## I only want to see those ppl whose age is above 30

In [ ]:
df3[df3["Age"]>= 30]

    Name  Age    City  Salary
1    Bob   30  London   62000
3  David   35  Sydney   75000

In [ ]:
#I only want to see those ppl whose age is above 30  and salary is above 65000

In [ ]:
df3[(df3["Age"]>= 30) & (df3["Salary"]>= 65000)]

    Name  Age    City  Salary
3  David   35  Sydney   75000