In [3]:
import numpy as np
import pandas as pd

## Finding Missing Data

In [4]:
data = {
    'A': [1, 2, None, 4],
    'B': [None, 6, 7, 8],
    'C': [9, None, 11, 12],
    'D': [13, 14, 15, None],
    'E': [17, 18, 19, 20]
}   

df1=pd.DataFrame(data)

In [5]:
df1

     A    B     C     D   E
0  1.0  NaN   9.0  13.0  17
1  2.0  6.0   NaN  14.0  18
2  NaN  7.0  11.0  15.0  19
3  4.0  8.0  12.0   NaN  20

In [6]:
df1.isna()

       A      B      C      D      E
0  False   True  False  False  False
1  False  False   True  False  False
2   True  False  False  False  False
3  False  False  False   True  False

In [7]:
df1.isna().sum()

A    1
B    1
C    1
D    1
E    0
dtype: int64

In [8]:
df1.isna().any()

A     True
B     True
C     True
D     True
E    False
dtype: bool

## Removing Missing Data

In [17]:
df1.dropna()

Empty DataFrame
Columns: [A, B, C, D, E]
Index: []

In [10]:
df1

     A    B     C     D   E
0  1.0  NaN   9.0  13.0  17
1  2.0  6.0   NaN  14.0  18
2  NaN  7.0  11.0  15.0  19
3  4.0  8.0  12.0   NaN  20

In [11]:
df1.dropna(thresh=3)

     A    B     C     D   E
0  1.0  NaN   9.0  13.0  17
1  2.0  6.0   NaN  14.0  18
2  NaN  7.0  11.0  15.0  19
3  4.0  8.0  12.0   NaN  20

## Filling The Missing Data

In [12]:
df1

     A    B     C     D   E
0  1.0  NaN   9.0  13.0  17
1  2.0  6.0   NaN  14.0  18
2  NaN  7.0  11.0  15.0  19
3  4.0  8.0  12.0   NaN  20

In [13]:
df1.fillna(0)

     A    B     C     D   E
0  1.0  0.0   9.0  13.0  17
1  2.0  6.0   0.0  14.0  18
2  0.0  7.0  11.0  15.0  19
3  4.0  8.0  12.0   0.0  20

In [14]:
values={"A":0,"B":1,"C":2,"D":3,"E":4}
df1.fillna(value=values)

     A    B     C     D   E
0  1.0  1.0   9.0  13.0  17
1  2.0  6.0   2.0  14.0  18
2  0.0  7.0  11.0  15.0  19
3  4.0  8.0  12.0   3.0  20

In [15]:
df1.fillna(df1.mean())

          A    B          C     D   E
0  1.000000  7.0   9.000000  13.0  17
1  2.000000  6.0  10.666667  14.0  18
2  2.333333  7.0  11.000000  15.0  19
3  4.000000  8.0  12.000000  14.0  20