In [4]:
import numpy as np
import pandas as pd

## Merging 2 Dataframes

In [5]:
employees = {
    "EmployeeID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 28, 35, 27],
    "City": ["New York", "London", "Mumbai", "Sydney", "Toronto"],
}

salaries={
        "EmployeeID": [101, 102, 103, 106, 107],
        "Salary": [55000, 62000, 48000, 75000, 59000],
        "Bonus": [5000, 6000, 4000, 7000, 5500]
}
Em=pd.DataFrame(employees)
Sa=pd.DataFrame(salaries)

In [6]:
Em

   EmployeeID     Name  Age      City
0         101    Alice   25  New York
1         102      Bob   30    London
2         103  Charlie   28    Mumbai
3         104    David   35    Sydney
4         105     Emma   27   Toronto

In [7]:
Sa

   EmployeeID  Salary  Bonus
0         101   55000   5000
1         102   62000   6000
2         103   48000   4000
3         106   75000   7000
4         107   59000   5500

In [8]:
pd.merge(Em,Sa,on="EmployeeID",how='inner')

   EmployeeID     Name  Age      City  Salary  Bonus
0         101    Alice   25  New York   55000   5000
1         102      Bob   30    London   62000   6000
2         103  Charlie   28    Mumbai   48000   4000

In [9]:
pd.merge(Em,Sa,on="EmployeeID",how='outer')

   EmployeeID     Name   Age      City   Salary   Bonus
0         101    Alice  25.0  New York  55000.0  5000.0
1         102      Bob  30.0    London  62000.0  6000.0
2         103  Charlie  28.0    Mumbai  48000.0  4000.0
3         104    David  35.0    Sydney      NaN     NaN
4         105     Emma  27.0   Toronto      NaN     NaN
5         106      NaN   NaN       NaN  75000.0  7000.0
6         107      NaN   NaN       NaN  59000.0  5500.0

In [10]:
pd.merge(Em,Sa,on="EmployeeID",how='left')

   EmployeeID     Name  Age      City   Salary   Bonus
0         101    Alice   25  New York  55000.0  5000.0
1         102      Bob   30    London  62000.0  6000.0
2         103  Charlie   28    Mumbai  48000.0  4000.0
3         104    David   35    Sydney      NaN     NaN
4         105     Emma   27   Toronto      NaN     NaN

In [13]:
pd.merge(Em,Sa,on="EmployeeID",how='right')

   EmployeeID     Name   Age      City  Salary  Bonus
0         101    Alice  25.0  New York   55000   5000
1         102      Bob  30.0    London   62000   6000
2         103  Charlie  28.0    Mumbai   48000   4000
3         106      NaN   NaN       NaN   75000   7000
4         107      NaN   NaN       NaN   59000   5500

## Concatination of 2 dataframes

In [30]:
df1=pd.DataFrame({ 
    "A":["A0","A1","A2"],
    "B":["B0","B1","B2"],
    "C":["C0","C1","C2"]})


df2=pd.DataFrame({
    "A":["A3","A4","A5"],
    "B":["B3","B4","B5"],
    "C":["C3","C4","C5"]
})

In [31]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [32]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [34]:
pd.concat([df1, df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [35]:
pd.concat([df1, df2] ,axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

## Joining of 2 Dataframes

In [13]:
df1=pd.DataFrame({
    "name":["Alice","Bob","Charlie"]
},index=[0,1,2])

df2=pd.DataFrame({
    "age":[25,30,28]
},index=[0,3,4])

In [37]:
df1

      name
0    Alice
1      Bob
2  Charlie

In [38]:
df2

   age
0   25
3   30
4   28

In [39]:
df1.join(df2)

      name   age
0    Alice  25.0
1      Bob   NaN
2  Charlie   NaN

In [40]:
df1.join(df2,how='outer')

      name   age
0    Alice  25.0
1      Bob   NaN
2  Charlie   NaN
3      NaN  30.0
4      NaN  28.0

In [41]:
df2.join(df1)

   age   name
0   25  Alice
3   30    NaN
4   28    NaN