In [6]:
import numpy as np
import pandas as pd

## DataFrame Basic Operations

In [8]:
df1=pd.DataFrame({
    "A":[1,2,3,4],
    "B":[10,20,30,40],
    "C":[100,200,300,400]
})

In [9]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400

In [10]:
df1.shape

(4, 3)

In [12]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [13]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int64
 1   B       4 non-null      int64
 2   C       4 non-null      int64
dtypes: int64(3)
memory usage: 228.0 bytes

In [14]:
df1.describe()

              A          B           C
count  4.000000   4.000000    4.000000
mean   2.500000  25.000000  250.000000
std    1.290994  12.909944  129.099445
min    1.000000  10.000000  100.000000
25%    1.750000  17.500000  175.000000
50%    2.500000  25.000000  250.000000
75%    3.250000  32.500000  325.000000
max    4.000000  40.000000  400.000000

In [16]:
df1["A"]+10

0    11
1    12
2    13
3    14
Name: A, dtype: int64

## DataFrames Applying Function

In [17]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400

In [18]:
def square(x):
    return x**2

In [27]:
df1["D"]=df1["B"].apply(lambda x: x**2)
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600